version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx
        depends_on:
            - flask
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - my-network
        ports:
            - 8080:80
    flask:
        build:
            context: ./app
            dockerfile: Dockerfile
        networks:
            my-network:
                aliases:
                    - flask-app
        ports:
            - 5000:5000

networks:
    my-network:
